services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: hack
      POSTGRES_PASSWORD: hackpwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgres://hack:hackpwd@postgres:5432/mydb"
      ADMIN_SECRET: letmein
      UPLOAD_DIR: /usr/src/app/uploads
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ../backend/uploads:/usr/src/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"        # browse to http://localhost:8080
    restart: unless-stopped
    # optional local dev mount (uncomment to use live dev files)
    # volumes:
    #   - ../frontend:/app:ro

volumes:
  pgdata:
