apiVersion: v1
kind: Secret
metadata:
  name: crowdclue-secrets
type: Opaque
stringData:
  ADMIN_SECRET: "letmein"
  JWT_SECRET: "dev_jwt_secret_change_me"
  DATABASE_URL: "postgres://hack:hackpwd@postgres:5432/mydb"
